services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/your_db_name  # Adjust for your environment
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend